### ISSUE TITLE
Display Setting

### ISSUE THREAD

**Issue by semuaitu8** [yuan910715/Esp8266_Wifi_Matrix_Clock#1]
this project so awesome, but when I try to change setting on display and I click submit, suddenly nothing appear on screen

**Comment by yuan910715** [comment]
hi , please tell me your board model and chip id ,and other setting pages is ok? thanks.

**Comment by semuaitu8** [comment]
my board is NodeMCU ESP8266 from Amica
I have tested other setting page and no problem

**Comment by yuan910715** [comment]
You can try another browser or another PC/phone, I checked the code, and did not find a bug that might cause this problem.
Did you use webUpload.ino to upload firmware?

**Comment by semuaitu8** [comment]
ok thanks, I will try it
yes, I used WebUpload.ino

**Comment by yuan910715** [comment]
@semuaitu8 hello, this is a bug, I add a new font but forgot to add settings on English page , I have fixed it on version 2.5 ,thanks.
