### ISSUE TITLE
Settings / Scroll setting

### ISSUE THREAD

**Issue by najmulhaq** [yuan910715/Esp8266_Wifi_Matrix_Clock#3]
Hi, this product is awesome !!

I found out that under Settings -> Scroll Settings, the text is written incorrectly as "Scrool Settings".

Please try to correct it in future versions.

Thanks
Najmulhaq

**Comment by yuan910715** [comment]
Hi 
I will correct it , thanks a lot.

**Comment by najmulhaq** [comment]
Hi, 
Thanks 👍Najmulhaq 

Sent from Yahoo Mail on Android 
 
  On Thu, 25 Mar 2021 at 2:30 PM, ***@***.***> wrote:   


Hi
I will correct it , thanks a lot.
